# Generated by Django 4.1.4 on 2022-12-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("century", models.CharField(max_length=10)),
                ("gender_specific", models.CharField(max_length=10)),
            ],
        ),
    ]
